package isms.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import isms.common.Supplier;

public abstract class BaseDao {

	protected interface PreparedStatementOperation {

		public void apply(PreparedStatement stmt) throws SQLException;
	}

	private Supplier<Connection> supplier;

	public void setSupplier(Supplier<Connection> supplier) {
		this.supplier = supplier;
	}

	private void run(String sql, PreparedStatementOperation op, int autoGeneratedKeys) {
		try (Connection connection = supplier.get();
				PreparedStatement stmt = connection.prepareStatement(sql, autoGeneratedKeys)) {
			op.apply(stmt);
		} catch (SQLException e) {
			throw new RuntimeException(e);
		}
	}

	protected void run(String sql, PreparedStatementOperation op, boolean generateKeys) {
		run(sql, op, generateKeys ? Statement.RETURN_GENERATED_KEYS : Statement.NO_GENERATED_KEYS);
	}
	
	protected void run(String sql, PreparedStatementOperation op) {
		run(sql, op, false);
	}

	protected Long insert(PreparedStatement stmt) throws SQLException {
		Long id = null;

		if (stmt.executeUpdate() > 0) {
			ResultSet keys = stmt.getGeneratedKeys();

			if (keys.next()) {
				id = keys.getLong(1);
			} else {
				throw new SQLException("No insert ID was found.");
			}
		} else {
			throw new SQLException("No rows were created during insert.");
		}

		return id;
	}

}
